import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import { Header } from "@/components/header";
import { Activities } from "@/components/activities";
import { Footer } from "@/components/footer";
import { InfoBanner } from "@/components/banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Quipa Oficial Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Activities />
        <InfoBanner />
        <Footer />
      </main>
    </>
  );
}
